name: Deploy

on:
  release:
    types: [published]

jobs:
  setup:
    uses: flitsmeister/backend-github-actions/.github/workflows/setup.yml@master
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    uses: flitsmeister/backend-github-actions/.github/workflows/deploy.yml@master
    needs: setup
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
