name: Deploy

on:
  release:
    types: [published]

jobs:
  setup18:
    uses: flitsmeister/backend-github-actions/.github/workflows/setup_njs18.yml@master
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  setup20:
    uses: flitsmeister/backend-github-actions/.github/workflows/setup_njs20.yml@master
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    uses: flitsmeister/backend-github-actions/.github/workflows/deploy.yml@master
    needs: [setup18, setup20]
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
